spring:
  # 数据源配置
  datasource:
    # 名称
    name: test
    # 数据库链接
    url: jdbc:mysql://119.23.35.90:33061/nobee?useUnicode=true&characterEncoding=UTF-8
    # 用户名
    username: nobee
    # 密码
    password: "nobee@2017"
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat, wall
    max-active: 20
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
  http:
    encoding:
      charset: utf-8
    multipart:
      max-file-size: 20mb
      max-request-size: 20mb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
  cas:
    service: "https://localhost:80/baseframe/login/cas"
    casurl: "https://localhost:8080/cas"
    loginurl: "https://localhost:8080/cas/login"
    logout: "https://localhost:8080/cas/logout"
    enable: false
  web:
    security:
      # 不拦截url
      ignoring: "/, /static/**/*, /login.jsp, /error, /login/cas, /page/mainContent.jsp, /page/error/404.jsp, /page/error/403.jsp,
      /page/error/500.jsp, /mp/core/**/*, /cp/core/**/*, /mp/menuCore/**/*, /cp/menuCore/**/*, /mp/auth/**/*, /api/**/*"
      # 拦截url
      intercept: ""
      # 登录成功跳转页面
      successUrl: "/index.jsp"
      # 注销成功跳转页面
      logoutSuccessUrl: "/login.jsp"
mybatis:
  config:
    # Mybatis model 路径
        typeAliasesPackage: com.ricelink.baseframe.bs.mapper.model, com.ricelink.baseframe.common.mapper.model
        reasonable: true
        supportMethodsArguments: true
        returnPageInfo: check
        params: count=countSql
        # Mybatis mapper xml 路径
        mapperLocations: classpath:mybatis/mapper/*.xml
        # Mybatis mapper interface 路径
        basePackage: com.ricelink.weixin.mapper.mapper, com.ricelink.baseframe.common.mapper.mapper
        # 通用 mapper 接口
        mappers: tk.mybatis.mapper.common.Mapper
        # 主键自增全局配置
        identity: MYSQL
        callSettersOnNulls: true
server:
  tomcat:
    uri-encoding: UTF-8
#  context-path: /nobee_weixin_ipad_api
#  port: 80
settings:
  hostsName: http://chenshengjv.viphk.ngrok.org
mp:
  token: chenSJ519
  appid: wxaa5560adbda88dbe
  appsecret: d4624c36b6795d1d99dcf0547af5443d
  aesKey: